### ISSUE TITLE
Enable `image-lookup`

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom-minimal-deployment-sample#13]
This repo requires `kustomize` so we can adjust the `image` setting on the `Deployment` in the YAML files.

OpenShift offers a feature called [`image-lookup`](https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#using-is-with-k8s) which coul dmake the above obsolete so we could reference `image: "hello-lagom:1.0-SNAPSHOT"` in all environments instead of requiring:

```
## in overlays/openshift/kustomization.yml
images:
  - name: "hello-lagom"
    newName: "docker-registry-default.centralpark.lightbend.com/lagom-scala-openshift-smoketests/hello-lagom"
```
